vault_addr: "https://vault.hashicorp.local:8200"
vault_approle_role_id: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
vault_approle_secret_id: "{{ lookup('env', 'VAULT_SECRET_ID') }}"
vault_pki_role: "gcve"
domain: "hashicorp.local"