---

- name: Bootstrap Vault Agent with TPM support
  hosts: all
  become: yes
  gather_facts: false
  roles:
    - vault_tpm

- name: Sign CSR via Vault using EE
  hosts: localhost
  gather_facts: no
  vars:
    inventory_hostname: "{{ hostvars['web-server-01']['inventory_hostname'] }}"
  roles:
    - vault_sign