---

- name: Bootstrap Vault Agent with TPM support
  hosts: all
  become: true
  gather_facts: false
  roles:
    - vault_tpm

- name: Sign CSR via Vault using EE
  hosts: localhost
  gather_facts: false
  vars:
    vault_addr: "https://vault.hashicorp.local:8200"
    vault_pki_role: "gcve"
    target_hostname: "{{ hostvars['web-server-01']['inventory_hostname'] }}"
    remote_csr_data: "{{ hostvars['web-server-01'].remote_csr_data_fact }}"  # Use the new fact here
    domain: "hashicorp.local"  # Replace with the actual domain
  roles:
    - vault_sign
